# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = yes, please :)

    bezier = smoothOut, 0.25, 0.9, 0.35, 1.0
    bezier = smoothInOut, 0.4, 0.0, 0.2, 1.0
    bezier = subtle, 0.22, 0.9, 0.3, 1.0
    bezier = stylish, 0.2, 1.0, 0.15, 1.0

    animation = windows, 1, 6, stylish
    animation = windowsOut, 1, 6, smoothInOut
    animation = border, 1, 9, subtle
    animation = fade, 1, 5, smoothInOut
    animation = layersIn, 1, 5, subtle, slide bottom
    animation = layersOut, 1, 4, smoothInOut, slide bottom
    animation = fadeLayersIn, 1, 4, subtle
    animation = fadeLayersOut, 1, 4, smoothInOut
    animation = workspaces, 1, 6, stylish, slide
}